name: CI

on: [pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Train model (smoke)
        run: python src/train.py
      - name: Run tests
        run: pytest -q
      - name: Build Docker image
        run: docker build -t my-ml-app:latest .

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag Docker image for ACR
        run: docker tag my-ml-app:latest ${{ secrets.ACR_LOGIN_SERVER }}/my-ml-app:latest

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-ml-app:latest

      # - name: Update Azure Container App with new image
      #   run: |
      #     az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      #     az containerapp update \
      #       --name ${{ secrets.ACA_NAME }} \
      #       --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
      #       --image ${{ secrets.ACR_LOGIN_SERVER }}/my-ml-app:latest
